site_name: mfractor docs
theme: readthedocs
copyright: Copyright &copy; 2016 <a href="https://www.mfractor.com">MFractor</a>
site_author: "Matthew Robbins"
site_description: "Documentation for MFractor for Mac, incredible Xamarin tools"
site_favicon: "img/favicon.ico"
repo_url: "https://github.com/mfractor/mfractor.github.io"
remote_branch: "master"
google_analytics: ['UA-71910290-3', 'docs.mfractor.com']
strict: true
theme_dir: theme
extra_css:
    - css/breadcrumbs.css
    - css/code.css
    - css/fabric.css
    - css/sidenav.css
    - css/mfractor.css

pages:
- Home: index.md
- Getting Started:
  - Installation And Setup: installation-and-setup.md
  - About MFractor Professional: mfractor-professional.md
  - FAQ: faq.md
  - Code Actions: code-actions.md
  - Working With Images: working-with-images.md
  - Using MFractor.Annotations: annotations.md
  - Configuration: configuration.md
- Xamarin.Forms:
  - Configuring A Binding Context: xamarin-forms/configure-binding-context.md
  - Navigation Tools: xamarin-forms/navigation.md
  - Analysis: xamarin-forms/analysis.md
  - Implementing View Models: xamarin-forms/implementing-view-models.md
  - Value Converter Type Safety: xamarin-forms/value-converter-type-safety.md
- Xamarin.Android:
  - Navigation Tools: xamarin-android/navigation-tools.md
  - Resource IntelliSense: xamarin-android/resource-intellisense.md
- Code Actions:
  - C# Code Actions: code-actions/csharp.md
  - Android Resource Code Actions:
    - Issue Fixing: code-actions/android-resources/fix.md
  - Xamarin.Forms Xaml Code Actions:
    - Issue Fixing: code-actions/xaml/fix.md
    - Code Generation: code-actions/xaml/generate.md
    - Xaml Organisation: code-actions/xaml/organise.md
    - Refactoring: code-actions/xaml/refactor.md
  - XML Code Actions: code-actions/xml.md
- Code Analysis:
  - C#:
    - Android C# Analysis: code-analysis/csharp/android.md
    - Xamarin.Forms C# Analysis: code-analysis/csharp/xamarin-forms.md
  - Android Resource Analysis: code-analysis/android-resources.md
  - Xamarin.Forms Xaml Analysis: code-analysis/xaml.md
  - MFractor Config Analysis: code-analysis/configuration.md
- Code Generation:
  - C#: code-generation/csharp.md
  - Xamarin.Forms - C#: code-generation/xamarin-forms.md
  - Xaml: code-generation/xaml.md
  - ResX: code-generation/resx.md
  - XML: code-generation/xml.md
- ResX:
  - Configuration: resx/configuration.md
- Release Notes:
    - v3.2: release-notes/v3-2.md
    - v3.1: release-notes/v3-1.md
    - v3.0: release-notes/v3-0.md
    - v2: release-notes/v2.md
