site_name: MFractor Documentation
copyright: Copyright &copy; 2015-2019 <a href="https://www.mfractor.com">MFractor Pty Ltd</a>
site_author: "MFractor Pty Ltd"
site_description: "Documentation for MFractor, a powerful productivity tool for Visual Studio"
repo_url: "https://github.com/mfractor/mfractor.github.io"
remote_branch: "master"
google_analytics: ['UA-71910290-3', 'docs.mfractor.com']
strict: true
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'blue'

nav:
- Home: index.md
- Getting Started - Windows:
  - Quickstart: windows/quickstart.md
  - Installation: windows/installation.md
  - Licensing And Activation: windows/activation.md
  - Upgrades: windows/upgrades.md
  - Uninstallation: windows/uninstallation.md
  - Reporting Issues: windows/reporting-issues.md
  - Frequently Asked Questions: windows/faq.md
- Getting Started  - Mac:
  - Quickstart: mac/quickstart.md
  - Installation: mac/installation.md
  - Licensing And Activation: mac/activation.md
  - Upgrades: mac/upgrades.md
  - Uninstallation: mac/uninstallation.md
  - Reporting Issues: mac/reporting-issues.md
  - Frequently Asked Questions: mac/faq.md
- Support: support.md
- Legal:
  - Privacy Policy: legal/privacy-policy.pdf
  - End User License: legal/end-user-license.pdf
